
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 21 2025 12:47:39 IST (Mar 21 2025 07:17:39 UTC)

// Verification Directory fv/s298 

module s298(CK, G0, G1, G117, G118, G132, G133, G2, G66, G67);
  input CK, G0, G1, G2;
  output G117, G118, G132, G133, G66, G67;
  wire CK, G0, G1, G2;
  wire G117, G118, G132, G133, G66, G67;
  wire G10, G11, G12, G13, G14, G15, G22, G23;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire n_1, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_40, n_41, n_42, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_69, n_70;
  DFF_X2 DFF_3_q_reg(.CK (CK), .D (n_67), .Q (n_19), .QN (G13));
  DFF_X1 DFF_10_q_reg(.CK (CK), .D (n_65), .Q (G132), .QN
       (UNCONNECTED));
  DFF_X1 DFF_9_q_reg(.CK (CK), .D (n_66), .Q (G118), .QN
       (UNCONNECTED0));
  DFF_X1 DFF_6_q_reg(.CK (CK), .D (n_64), .Q (G66), .QN (UNCONNECTED1));
  OAI22_X2 g1233__2398(.A1 (G0), .A2 (n_58), .B1 (n_44), .B2 (G13), .ZN
       (n_67));
  DFF_X2 DFF_5_q_reg(.CK (CK), .D (n_63), .Q (n_20), .QN (G15));
  DFF_X1 DFF_7_q_reg(.CK (CK), .D (n_59), .Q (G67), .QN (UNCONNECTED2));
  DFF_X2 DFF_4_q_reg(.CK (CK), .D (n_60), .Q (n_36), .QN (G14));
  INV_X2 g1238(.A (n_61), .ZN (n_66));
  OAI211_X2 g1232__5107(.A (n_35), .B (n_46), .C1 (n_62), .C2 (G10),
       .ZN (n_65));
  DFF_X1 DFF_8_q_reg(.CK (CK), .D (n_70), .Q (G117), .QN
       (UNCONNECTED3));
  INV_X4 g1239(.A (n_56), .ZN (n_64));
  NOR2_X2 g1240__6260(.A1 (G0), .A2 (n_62), .ZN (n_63));
  AOI211_X2 g1241__4319(.A (n_47), .B (n_55), .C1 (n_54), .C2 (G118),
       .ZN (n_61));
  NOR2_X2 g1235__8428(.A1 (n_49), .A2 (G0), .ZN (n_60));
  INV_X2 g1247(.A (n_53), .ZN (n_59));
  DFF_X1 DFF_11_q_reg(.CK (CK), .D (n_51), .Q (G133), .QN
       (UNCONNECTED4));
  INV_X4 g1248(.A (n_52), .ZN (n_58));
  AOI21_X2 g1242__6783(.A (n_55), .B1 (n_54), .B2 (G66), .ZN (n_56));
  AOI22_X2 g1243__3680(.A1 (n_37), .A2 (n_20), .B1 (n_9), .B2 (n_32),
       .ZN (n_62));
  DFF_X2 DFF_1_q_reg(.CK (CK), .D (n_45), .Q (n_12), .QN (G11));
  AOI221_X2 g1249__1617(.A (n_42), .B1 (n_23), .B2 (G11), .C1 (n_54),
       .C2 (G67), .ZN (n_53));
  OAI21_X2 g1251__2802(.A (n_48), .B1 (n_38), .B2 (G12), .ZN (n_52));
  DFF_X2 DFF_2_q_reg(.CK (CK), .D (n_41), .Q (UNCONNECTED5), .QN (G12));
  OAI21_X2 g1258__1705(.A (n_40), .B1 (n_50), .B2 (n_8), .ZN (n_51));
  XNOR2_X2 g1250__5122(.A (n_31), .B (G14), .ZN (n_49));
  AOI221_X2 g1253__8246(.A (n_36), .B1 (n_48), .B2 (n_24), .C1 (n_30),
       .C2 (G22), .ZN (n_55));
  OAI21_X2 g1257__7098(.A (n_46), .B1 (n_21), .B2 (G10), .ZN (n_47));
  DFF_X2 DFF_13_q_reg(.CK (CK), .D (n_34), .Q (n_16), .QN (G23));
  OAI21_X2 g1259__6131(.A (n_33), .B1 (n_44), .B2 (G11), .ZN (n_45));
  NOR2_X2 g1254__1881(.A1 (G0), .A2 (n_29), .ZN (n_41));
  NAND2_X2 g1261__5115(.A1 (n_54), .A2 (G133), .ZN (n_40));
  DFF_X2 DFF_12_q_reg(.CK (CK), .D (n_28), .Q (G22), .QN
       (UNCONNECTED6));
  AOI22_X2 g1267__4733(.A1 (n_15), .A2 (G13), .B1 (G11), .B2 (n_19),
       .ZN (n_38));
  OR3_X2 g1268__6161(.A1 (n_48), .A2 (G22), .A3 (n_36), .ZN (n_37));
  NAND2_X2 g1264__9315(.A1 (n_54), .A2 (G132), .ZN (n_35));
  NOR2_X2 g1266__9945(.A1 (n_27), .A2 (G11), .ZN (n_42));
  NOR2_X2 g1262__2883(.A1 (n_17), .A2 (G0), .ZN (n_34));
  OR3_X1 g1269__2346(.A1 (G0), .A2 (n_10), .A3 (n_32), .ZN (n_33));
  DFF_X2 DFF_0_q_reg(.CK (CK), .D (n_22), .Q (G10), .QN (n_7));
  AOI21_X2 g1272__1666(.A (n_16), .B1 (n_11), .B2 (n_32), .ZN (n_31));
  INV_X4 g1273(.A (n_25), .ZN (n_30));
  XNOR2_X2 g1270__7410(.A (n_14), .B (G12), .ZN (n_29));
  NAND3_X2 g1271__6417(.A1 (n_26), .A2 (G11), .A3 (n_36), .ZN (n_46));
  NOR2_X2 g1265__5477(.A1 (n_13), .A2 (G0), .ZN (n_28));
  INV_X2 g1274(.A (n_26), .ZN (n_27));
  AOI21_X2 g1276__2398(.A (n_24), .B1 (G11), .B2 (G12), .ZN (n_25));
  INV_X1 g1280(.A (n_23), .ZN (n_50));
  NAND2_X2 g1278__5107(.A1 (n_32), .A2 (n_12), .ZN (n_48));
  AND3_X4 g1285__6260(.A1 (n_36), .A2 (n_18), .A3 (G15), .ZN (n_54));
  INV_X1 g1291(.A (n_44), .ZN (n_22));
  AOI21_X2 g1275__4319(.A (n_20), .B1 (G14), .B2 (n_19), .ZN (n_21));
  NOR2_X2 g1277__8428(.A1 (n_20), .A2 (n_18), .ZN (n_26));
  XNOR2_X2 g1283__5526(.A (G1), .B (n_16), .ZN (n_17));
  INV_X2 g1290(.A (n_14), .ZN (n_15));
  NOR3_X2 g1284__6783(.A1 (n_36), .A2 (n_20), .A3 (n_19), .ZN (n_23));
  XNOR2_X2 g1281__3680(.A (G2), .B (G22), .ZN (n_13));
  NAND2_X2 g1294__1617(.A1 (n_12), .A2 (G10), .ZN (n_14));
  NAND2_X2 g1295__2802(.A1 (n_1), .A2 (n_7), .ZN (n_44));
  INV_X2 g1286(.A (n_10), .ZN (n_11));
  AND3_X2 g1282__1705(.A1 (G11), .A2 (G22), .A3 (G14), .ZN (n_9));
  NAND2_X1 g1288__5122(.A1 (G15), .A2 (n_19), .ZN (n_24));
  AND2_X4 g1289__8246(.A1 (n_19), .A2 (G12), .ZN (n_32));
  OR2_X4 g1292__7098(.A1 (G11), .A2 (G12), .ZN (n_8));
  NAND2_X2 g1293__6131(.A1 (G12), .A2 (G13), .ZN (n_18));
  NAND2_X2 g1287__1881(.A1 (G11), .A2 (G10), .ZN (n_10));
  INV_X4 g1307(.A (G0), .ZN (n_1));
  NAND2_X1 g2(.A1 (n_69), .A2 (n_50), .ZN (n_70));
  AOI21_X1 g3(.A (n_42), .B1 (n_54), .B2 (G117), .ZN (n_69));
endmodule

